language: rust
cache: cargo
sudo: false
rust:
- nightly
- beta
- stable
env:
  matrix:
  - FEATURES=""
  - FEATURES="unstable"
matrix:
  exclude:
  - rust: beta
    env: FEATURES="unstable"
  - rust: stable
    env: FEATURES="unstable"
script: |
  cargo build --verbose --features "${FEATURES}"
  cargo test --verbose --features "${FEATURES}"
  cargo build --verbose --manifest-path evaluate/Cargo.toml
