language: rust
sudo: false
rust:
  - nightly
  - beta
env:
  - FEATURES=""
  - FEATURES="unstable"
matrix:
  exclude:
    - rust: beta
      env: FEATURES="unstable"
script: |
  cargo build --verbose --features "${FEATURES}"
  cargo test --verbose --features "${FEATURES}"
