[package]

name = "xpath"
version = "0.0.1"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]

[features]

unstable = []

[dependencies]

getopts = "0.2.4"
peresil = "0.2.0"

[dependencies.document]

git = "https://github.com/shepmaster/sxd-document.git"
